# Generated by Django 5.2 on 2025-04-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICA', 'Electronica'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('BIENESTAR', 'Bienestar'), ('OTROS', 'Otros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='defaulr.png', upload_to='product_pic'),
        ),
    ]
