# Generated by Django 5.1.7 on 2025-03-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ROPA', 'Ropa'), ('CALZADO', 'Calzado')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
